"""Preserve the reviewed trained feature definition without executing notebook cells."""
import argparse
import ast
import hashlib
import json
from pathlib import Path

NOTEBOOK_SHA = 'e760268cb1d1fd0dfc40bf8c632cfcb2485040d4c6e44172cee37472b5601a6f'


def build(path):
    raw = Path(path).read_bytes()
    if hashlib.sha256(raw).hexdigest() != NOTEBOOK_SHA:
        raise ValueError('Use the reviewed notebook version')
    notebook = json.loads(raw)
    selected = []
    for cell in notebook['cells']:
        if cell['cell_type'] != 'code':
            continue
        source = ''.join(cell['source'])
        for node in ast.parse(source).body:
            if isinstance(node, ast.FunctionDef) and node.name == 'add_model_features':
                selected.append(ast.get_source_segment(source, node))
    if len(selected) != 1:
        raise ValueError('Expected one feature function')
    header = '''"""Exact trained category-feature equations from the reviewed notebook.

Generated by build_category_feature_source.py. Input panel is validated and
bounded by category_lstm_frozen.py; no notebook globals or model loading here.
"""
import numpy as np
import pandas as pd

USER_COL = 'user_id'
SPEND_COLS = [f'spend_{i}' for i in range(9)]
COUNT_COLS = [f'count_{i}' for i in range(9)]

'''
    return header+selected[0]+'\n'


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--notebook', type=Path, required=True)
    args = p.parse_args()
    output = Path(__file__).with_name('category_lstm_features.py')
    with output.open('x', encoding='utf-8', newline='\n') as f:
        f.write(build(args.notebook))
