"""Exact trained category-feature equations from the reviewed notebook.

Generated by build_category_feature_source.py. Input panel is validated and
bounded by category_lstm_frozen.py; no notebook globals or model loading here.
"""
import numpy as np
import pandas as pd

USER_COL = 'user_id'
SPEND_COLS = [f'spend_{i}' for i in range(9)]
COUNT_COLS = [f'count_{i}' for i in range(9)]

def add_model_features(panel):

    x = (
        panel
        .sort_values(
            [
                USER_COL,
                "week"
            ]
        )
        .reset_index(
            drop=True
        )
        .copy()
    )


    # --------------------------------------------------------
    # Overall weekly behaviour
    # --------------------------------------------------------

    x[
        "log_total_spend"
    ] = np.log1p(
        x["total_spend"]
    )

    x[
        "log_total_count"
    ] = np.log1p(
        x["total_count"]
    )


    safe_total = (
        x["total_spend"]
        .replace(
            0,
            np.nan
        )
    )


    feature_cols = []


    # --------------------------------------------------------
    # Per-category behaviour
    # --------------------------------------------------------

    for i, (
        spend_col,
        count_col
    ) in enumerate(
        zip(
            SPEND_COLS,
            COUNT_COLS
        )
    ):

        # ----------------------------
        # Existing current-week data
        # ----------------------------

        log_spend_col = (
            f"log_spend_{i}"
        )

        log_count_col = (
            f"log_count_{i}"
        )

        share_col = (
            f"share_{i}"
        )


        x[
            log_spend_col
        ] = np.log1p(
            x[spend_col]
        )

        x[
            log_count_col
        ] = np.log1p(
            x[count_col]
        )

        x[
            share_col
        ] = (
            x[spend_col]
            / safe_total
        ).fillna(
            0.0
        )


        # ----------------------------------------------------
        # Existing short-term activity history
        # ----------------------------------------------------

        for window in [
            4,
            8,
            13
        ]:

            col = (
                f"prior_active_rate"
                f"{window}_{i}"
            )

            x[col] = (
                x
                .groupby(
                    USER_COL
                )[spend_col]
                .transform(
                    lambda s:
                    (
                        s.gt(0)
                        .astype(float)
                        .shift(1)
                        .rolling(
                            window,
                            min_periods=1
                        )
                        .mean()
                        .fillna(0.0)
                    )
                )
            )


        # ----------------------------------------------------
        # NEW: same period approximately one year earlier
        # ----------------------------------------------------

        yearly_lag = (
            x
            .groupby(
                USER_COL
            )[spend_col]
            .shift(52)
            .fillna(0.0)
        )

        yearly_col = (
            f"log_spend_lag52_{i}"
        )

        x[
            yearly_col
        ] = np.log1p(
            yearly_lag
        )


        # ----------------------------------------------------
        # NEW: prior 13-week spending baseline
        # ----------------------------------------------------

        prior_mean_13 = (
            x
            .groupby(
                USER_COL
            )[spend_col]
            .transform(
                lambda s:
                (
                    s.shift(1)
                    .rolling(
                        13,
                        min_periods=4
                    )
                    .mean()
                )
            )
            .fillna(0.0)
        )

        mean13_col = (
            f"log_prior_mean13_{i}"
        )

        x[
            mean13_col
        ] = np.log1p(
            prior_mean_13
        )


        feature_cols.extend([
            log_spend_col,
            log_count_col,
            share_col,

            f"prior_active_rate4_{i}",
            f"prior_active_rate8_{i}",
            f"prior_active_rate13_{i}",

            yearly_col,
            mean13_col,
        ])


    # --------------------------------------------------------
    # Calendar seasonality
    # --------------------------------------------------------

    week_number = (
        x["week"]
        .dt
        .isocalendar()
        .week
        .astype(int)
    )

    x[
        "week_sin"
    ] = np.sin(
        2
        * np.pi
        * week_number
        / 52.0
    )

    x[
        "week_cos"
    ] = np.cos(
        2
        * np.pi
        * week_number
        / 52.0
    )


    feature_cols.extend([
        "log_total_spend",
        "log_total_count",
        "week_sin",
        "week_cos",
    ])


    return (
        x,
        feature_cols
    )
